<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net48</TargetFramework>
    <LangVersion>13</LangVersion>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <OutputType>Library</OutputType>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="ESBuild.MSBuild" Version="0.19.5.38" />
    <PackageReference Include="HtmlAgilityPack" Version="1.12.1" />
    <PackageReference Include="Microsoft.Extensions.FileSystemGlobbing" Version="9.0.5" />
    <PackageReference Include="Newtonsoft.Json" Version="13.0.3" />
    <PackageReference Include="System.Text.Json" Version="9.0.7" />
    <Reference Include="System.Web" />
    <Reference Include="System.Configuration" />
    <PackageReference Include="PolySharp" Version="1.15.0">
      <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
      <PrivateAssets>all</PrivateAssets>
    </PackageReference>
    <Reference Include="System.Web.Abstractions">
      <HintPath>..\..\..\..\.nuget\packages\microsoft.netframework.referenceassemblies.net48\1.0.3\build\.NETFramework\v4.8\System.Web.Abstractions.dll</HintPath>
    </Reference>
    <Reference Include="System.Web.ApplicationServices">
      <HintPath>..\..\..\..\.nuget\packages\microsoft.netframework.referenceassemblies.net48\1.0.3\build\.NETFramework\v4.8\System.Web.ApplicationServices.dll</HintPath>
    </Reference>
    <Reference Include="System.Web.RegularExpressions">
      <HintPath>..\..\..\..\.nuget\packages\microsoft.netframework.referenceassemblies.net48\1.0.3\build\.NETFramework\v4.8\System.Web.RegularExpressions.dll</HintPath>
    </Reference>
    <Reference Include="System.Web.Routing">
      <HintPath>..\..\..\..\.nuget\packages\microsoft.netframework.referenceassemblies.net48\1.0.3\build\.NETFramework\v4.8\System.Web.Routing.dll</HintPath>
    </Reference>
    <Reference Include="System.Web.Services">
      <HintPath>..\..\..\..\.nuget\packages\microsoft.netframework.referenceassemblies.net48\1.0.3\build\.NETFramework\v4.8\System.Web.Services.dll</HintPath>
    </Reference>
  </ItemGroup>

</Project>
